### PR TITLE
Create parser combinator library

### PR DESCRIPTION
**Pull request by pskfyi**
Finally done 👏  It's ginormous but a lot of work has been done that should make it easier to review:

- More than half of the changes are tests and JSDocs comments.

- The PR is divided into 4 commits.

- The monolithic `combinator.ts` file has been decomposed as much as possible without impairing maintainability.

  - `parser/core.ts` exports foundational types and an [abstract class](https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members) `CoreParser` which underpins all others.
 
  - `parser/ignored.ts` and `parser/Parser.ts` build on top of `CoreParser`.

  - `parser/RegExpParser.ts` builds on top of `Parser`.

  - `parser/string.ts`, `parser/regexp.ts`, and `parser/sequence.ts` build on top of the above.

  - `parser/named.ts` houses the short, reusable parsers that don't take inputs such as `whitespace` and `end`.

### CODE REVIEW

**Comment by AustinArey** [comment]
Amazing work, thanks for the great documentation. I'll take some notes as I go through this beast.

**Comment by AustinArey** [comment]
> Amazing work, thanks for the great documentation. I'll take some notes as I go through this beast.

[ ] Commit message of init(parser): End of line 8 typo of "stings." should be "strings."

**Review by AustinArey — CHANGES_REQUESTED** [review]
Looks great I just saw a couple typos in the commit messages 
 - [ ] Commit message of feat(parser): init -> End of line 8 typo of "stings." should be "strings."
 - [ ] Commit message of feat(parser): init -> Line 11 typo of "RagExp"

**Comment by pskfyi** [comment]
Thanks! Great catches.

**Review by AustinArey — APPROVED** [review]
Most Excellent work.

**Pull request merged**
