### PR TITLE
All Tests pass on Linux

### LINKED ISSUE #15: Enable testing for Linux in CI
Issues currently unknown. Needs triaging.

### PR DESCRIPTION
**Pull request by AustinArey**
Closes #15 

Test still hangs at the end (after all tests) before showing results, 4min later

### CODE REVIEW

**Comment by pskfyi** [comment]
Switched target branch to `0.3.0` where the CI jobs are defined, then closed & reopened to trigger CI.

**Comment by pskfyi** [comment]
Awesome stuff! 👏  Looks like it's only failing on a `fmt` error. Might be fixable by running `deno fmt` locally.

Also the CI job is still configured mac only:

https://github.com/pskfyi/handy/blob/f530ea80af1e4f6fe52500632a249d59e6c9e3b6/.github/workflows/pr-checks.yml#L40

I think you want to change this to `if: (matrix.os == 'macos-latest') || (matrix.os == 'ubuntu-latest')`.

You may need to rebase on top of `0.3.0` to get the most up-to-date state of the rest of the repo, including the GitHub Actions workflow file referenced above. Here are the rebase steps for reference:

```sh
git checkout 0.3.0
git pull # updates 0.3.0 to latest from GitHub
git checkout glob-tests-pass-linux
git rebase 0.3.0 # replay your commits on top of latest 0.3.0
```

**Comment by AustinArey** [comment]
Weird. When I run `deno fmt` locally everything passes...

**Review by pskfyi — COMMENTED** [review]
Sweet! Can you enable the tests too? My previous comment shows the steps.

**Comment by AustinArey** [comment]
I don't see the ./.github folder after pulling the latest 0.3.0. We need to merge this first right?

image

**Comment by AustinArey** [comment]
Added a step to install xclip.  It now fails on `copy()` not sure why. Locally everything passes (even though it takes 1-7 minutes....)

**Review by pskfyi — APPROVED** [review]
AMAZIN'!

**Pull request merged**
